name: santorini
version: 0.1.0
license: Apache-2.0
copyright: (c) 2021 Yosuke Mizutani
author: Yosuke Mizutani <yos@cs.utah.edu>
maintainer: Yosuke Mizutani <yos@cs.utah.edu>

ghc-options: -Wall

dependencies:
  - base == 4.*
  - containers
  - random
  - aeson
  - string-conversions
  - split
  - vector
  - hashtables
  - QuickCheck

library:
  source-dirs: src

executables:
  santorini-player:
    main: player.hs
    source-dirs: [src]
    dependencies: [santorini]

tests:
  santorini-test:
    main: Main.hs
    source-dirs:
      - test
    defaults: hspec/hspec@master
    dependencies:
      - santorini
      - hspec
